#!/bin/sh

if ! head -1 "$1" | grep -qE "^(init|feat|fix|ci|chore|docs|test|style|refactor|perf|build|revert)(\(.+?\))?: .{1,}$"; then
    echo -e "\e[31m ⚠ Commit cancelled. Please change your commit message to a Conventional Commits one. ⚠ \e[0m" >&2
    exit 1
fi

if ! head -1 "$1" | grep -qE "^.{1,88}$"; then
    echo -e "\e[31m ⚠ Commit cancelled. Your commit message is too long. ⚠ \e[0m" >&2
    exit 1
fi